---
- name: Install Apache server
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install httpd on Amazon Linux
      ansible.builtin.dnf:
        name: httpd
        state: latest
      when: ansible_distribution == 'Amazon'

    - name: Start httpd on Amazon Linux
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == 'Amazon'

    - name: Install apache2 on Ubuntu
      ansible.builtin.apt:
        name: apache2
        state: latest
      when: ansible_distribution == 'Ubuntu'

    - name: Start apache2 on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == 'Ubuntu'
